cursor #e0e3e5
cursor_text_color #bfc8cd

foreground            #e0e3e5
background            #101415
selection_foreground  #1b343d
selection_background  #b1cbd6
url_color             #8bd0ec

color0   #101415
color1   #ff72a0
color2   #76ec83
color3   #fff672
color4   #71c0e0
color5   #1a556d
color6   #8bd0ec
color7   #e8f3f7
color8   #8d9699
color9   #ff9fbe
color10  #a5ffaf
color11  #fff9a5
color12  #a5e5ff
color13  #b5e9ff
color14  #cff1ff
color15  #f8fdff
