cursor #171c1f
cursor_text_color #3e484e

foreground            #171c1f
background            #f6fafe
selection_foreground  #ffffff
selection_background  #a6cce1
url_color             #006687

color0   #0f1417
color1   #80002a
color2   #00650a
color3   #a29700
color4   #006b8d
color5   #a2dcee
color6   #006687
color7   #222525
color8   #6d7172
color9   #ca3852
color10  #00940f
color11  #afa400
color12  #0b789e
color13  #a2dcee
color14  #579aaf
color15  #c2c8ca
