cursor #f6ddd6
cursor_text_color #e0bfb5

foreground            #f6ddd6
background            #1c110d
selection_foreground  #55200c
selection_background  #ffb59c
url_color             #ffb59c

color0   #1c110d
color1   #ff7672
color2   #98ff7f
color3   #ffe572
color4   #f29d81
color5   #763721
color6   #ffb59c
color7   #fff3ef
color8   #47413f
color9   #ffa29f
color10  #b6ffa5
color11  #ffeea5
color12  #ffc0aa
color13  #ffcbb9
color14  #ffddd2
color15  #fffaf8
