[ColorScheme]
active_colors=#1b1b1b, #f9f9f9, #eeeeee, #777777, #e2e2e2, #c6c6c6, #1b1b1b, #1b1b1b, #1b1b1b, #f9f9f9, #f9f9f9, #000000, #000000, #e2e2e2, #5e5e5e, #5e5e5e, #f3f3f3, #f9f9f9, #f9f9f9, #474747, #474747
disabled_colors=#474747, #e2e2e2, #eeeeee, #777777, #e2e2e2, #c6c6c6, #474747, #474747, #474747, #e2e2e2, #e2e2e2, #000000, #e2e2e2, #474747, #474747, #474747, #e2e2e2, #e2e2e2, #e2e2e2, #474747, #474747
inactive_colors=#474747, #f9f9f9, #eeeeee, #777777, #e2e2e2, #c6c6c6, #474747, #474747, #474747, #f9f9f9, #f9f9f9, #000000, #5e5e5e, #ffffff, #5e5e5e, #5e5e5e, #f3f3f3, #f9f9f9, #f9f9f9, #474747, #474747

[ColorEffects:Disabled]
Color=71,71,71
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=119,119,119
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=238,238,238
BackgroundNormal=249,249,249
DecorationFocus=0,0,0
DecorationHover=0,0,0
ForegroundActive=0,0,0
ForegroundInactive=71,71,71
ForegroundLink=59,59,59
ForegroundNegative=186,26,26
ForegroundNeutral=94,94,94
ForegroundNormal=27,27,27
ForegroundPositive=59,59,59
ForegroundVisited=94,94,94

[Colors:Complementary]
BackgroundAlternate=238,238,238
BackgroundNormal=249,249,249
DecorationFocus=0,0,0
DecorationHover=0,0,0
ForegroundActive=0,0,0
ForegroundInactive=71,71,71
ForegroundLink=59,59,59
ForegroundNegative=186,26,26
ForegroundNeutral=94,94,94
ForegroundNormal=27,27,27
ForegroundPositive=59,59,59
ForegroundVisited=94,94,94

[Colors:Header]
BackgroundAlternate=249,249,249
BackgroundNormal=249,249,249
DecorationFocus=0,0,0
DecorationHover=0,0,0
ForegroundActive=0,0,0
ForegroundInactive=71,71,71
ForegroundLink=59,59,59
ForegroundNegative=186,26,26
ForegroundNeutral=94,94,94
ForegroundNormal=27,27,27
ForegroundPositive=59,59,59
ForegroundVisited=94,94,94

[Colors:Header][Inactive]
BackgroundAlternate=249,249,249
BackgroundNormal=249,249,249
DecorationFocus=0,0,0
DecorationHover=0,0,0
ForegroundActive=0,0,0
ForegroundInactive=71,71,71
ForegroundLink=59,59,59
ForegroundNegative=186,26,26
ForegroundNeutral=94,94,94
ForegroundNormal=27,27,27
ForegroundPositive=59,59,59
ForegroundVisited=94,94,94

[Colors:Selection]
BackgroundAlternate=59,59,59
BackgroundNormal=0,0,0
DecorationFocus=0,0,0
DecorationHover=0,0,0
ForegroundActive=226,226,226
ForegroundInactive=71,71,71
ForegroundLink=59,59,59
ForegroundNegative=186,26,26
ForegroundNeutral=94,94,94
ForegroundNormal=226,226,226
ForegroundPositive=59,59,59
ForegroundVisited=94,94,94

[Colors:Tooltip]
BackgroundAlternate=249,249,249
BackgroundNormal=249,249,249
DecorationFocus=0,0,0
DecorationHover=0,0,0
ForegroundActive=0,0,0
ForegroundInactive=71,71,71
ForegroundLink=59,59,59
ForegroundNegative=186,26,26
ForegroundNeutral=94,94,94
ForegroundNormal=27,27,27
ForegroundPositive=59,59,59
ForegroundVisited=94,94,94

[Colors:View]
BackgroundAlternate=243,243,243
BackgroundNormal=249,249,249
DecorationFocus=0,0,0
DecorationHover=0,0,0
ForegroundActive=0,0,0
ForegroundInactive=71,71,71
ForegroundLink=59,59,59
ForegroundNegative=186,26,26
ForegroundNeutral=94,94,94
ForegroundNormal=27,27,27
ForegroundPositive=59,59,59
ForegroundVisited=94,94,94

[Colors:Window]
BackgroundAlternate=249,249,249
BackgroundNormal=249,249,249
DecorationFocus=0,0,0
DecorationHover=0,0,0
ForegroundActive=0,0,0
ForegroundInactive=71,71,71
ForegroundLink=59,59,59
ForegroundNegative=186,26,26
ForegroundNeutral=94,94,94
ForegroundNormal=27,27,27
ForegroundPositive=59,59,59
ForegroundVisited=94,94,94

[WM]
activeBackground=249,249,249
activeBlend=27,27,27
activeForeground=27,27,27
inactiveBackground=249,249,249
inactiveBlend=71,71,71
inactiveForeground=71,71,71
