[ColorScheme]
active_colors=#271818, #fff8f7, #ffe9e8, #8e7070, #ffdada, #e2bebe, #271818, #ffffff, #271818, #fff8f7, #fff8f7, #000000, #b21533, #ffffff, #9c4147, #9c4147, #fff0f0, #fff8f7, #fff8f7, #5a4041, #5a4041
disabled_colors=#5a4041, #ffdada, #ffe9e8, #8e7070, #ffdada, #e2bebe, #5a4041, #5a4041, #5a4041, #ffdada, #ffdada, #000000, #ffdada, #5a4041, #5a4041, #5a4041, #ffdada, #ffdada, #ffdada, #5a4041, #5a4041
inactive_colors=#5a4041, #fff8f7, #ffe9e8, #8e7070, #ffdada, #e2bebe, #5a4041, #5a4041, #5a4041, #fff8f7, #fff8f7, #000000, #9c4147, #ffffff, #9c4147, #9c4147, #fff0f0, #fff8f7, #fff8f7, #5a4041, #5a4041

[ColorEffects:Disabled]
Color=90,64,65
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=142,112,112
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=255,233,232
BackgroundNormal=255,248,247
DecorationFocus=178,21,51
DecorationHover=178,21,51
ForegroundActive=178,21,51
ForegroundInactive=90,64,65
ForegroundLink=141,72,0
ForegroundNegative=186,26,26
ForegroundNeutral=156,65,71
ForegroundNormal=39,24,24
ForegroundPositive=141,72,0
ForegroundVisited=156,65,71

[Colors:Complementary]
BackgroundAlternate=255,233,232
BackgroundNormal=255,248,247
DecorationFocus=178,21,51
DecorationHover=178,21,51
ForegroundActive=178,21,51
ForegroundInactive=90,64,65
ForegroundLink=141,72,0
ForegroundNegative=186,26,26
ForegroundNeutral=156,65,71
ForegroundNormal=39,24,24
ForegroundPositive=141,72,0
ForegroundVisited=156,65,71

[Colors:Header]
BackgroundAlternate=255,248,247
BackgroundNormal=255,248,247
DecorationFocus=178,21,51
DecorationHover=178,21,51
ForegroundActive=178,21,51
ForegroundInactive=90,64,65
ForegroundLink=141,72,0
ForegroundNegative=186,26,26
ForegroundNeutral=156,65,71
ForegroundNormal=39,24,24
ForegroundPositive=141,72,0
ForegroundVisited=156,65,71

[Colors:Header][Inactive]
BackgroundAlternate=255,248,247
BackgroundNormal=255,248,247
DecorationFocus=178,21,51
DecorationHover=178,21,51
ForegroundActive=178,21,51
ForegroundInactive=90,64,65
ForegroundLink=141,72,0
ForegroundNegative=186,26,26
ForegroundNeutral=156,65,71
ForegroundNormal=39,24,24
ForegroundPositive=141,72,0
ForegroundVisited=156,65,71

[Colors:Selection]
BackgroundAlternate=213,51,73
BackgroundNormal=178,21,51
DecorationFocus=178,21,51
DecorationHover=178,21,51
ForegroundActive=255,255,255
ForegroundInactive=90,64,65
ForegroundLink=141,72,0
ForegroundNegative=186,26,26
ForegroundNeutral=156,65,71
ForegroundNormal=255,255,255
ForegroundPositive=141,72,0
ForegroundVisited=156,65,71

[Colors:Tooltip]
BackgroundAlternate=255,248,247
BackgroundNormal=255,248,247
DecorationFocus=178,21,51
DecorationHover=178,21,51
ForegroundActive=178,21,51
ForegroundInactive=90,64,65
ForegroundLink=141,72,0
ForegroundNegative=186,26,26
ForegroundNeutral=156,65,71
ForegroundNormal=39,24,24
ForegroundPositive=141,72,0
ForegroundVisited=156,65,71

[Colors:View]
BackgroundAlternate=255,240,240
BackgroundNormal=255,248,247
DecorationFocus=178,21,51
DecorationHover=178,21,51
ForegroundActive=178,21,51
ForegroundInactive=90,64,65
ForegroundLink=141,72,0
ForegroundNegative=186,26,26
ForegroundNeutral=156,65,71
ForegroundNormal=39,24,24
ForegroundPositive=141,72,0
ForegroundVisited=156,65,71

[Colors:Window]
BackgroundAlternate=255,248,247
BackgroundNormal=255,248,247
DecorationFocus=178,21,51
DecorationHover=178,21,51
ForegroundActive=178,21,51
ForegroundInactive=90,64,65
ForegroundLink=141,72,0
ForegroundNegative=186,26,26
ForegroundNeutral=156,65,71
ForegroundNormal=39,24,24
ForegroundPositive=141,72,0
ForegroundVisited=156,65,71

[WM]
activeBackground=255,248,247
activeBlend=39,24,24
activeForeground=39,24,24
inactiveBackground=255,248,247
inactiveBlend=90,64,65
inactiveForeground=90,64,65
