[Appearance]
color_scheme_path=/home/afu/.local/share/color-schemes/DankMatugen.colors
custom_palette=true
icon_theme=Papirus

[Fonts]
fixed="Maple Mono NF CN,11,-1,5,50,0,0,0,0,0"
general="Maple Mono NF CN,11,-1,5,50,0,0,0,0,0"
